-- 코드를 작성해주세요
WITH TEMP_TABLE AS (
    SELECT PARENT_ID AS ID, COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
)
SELECT O.ID, COALESCE(CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA O LEFT JOIN TEMP_TABLE T ON O.ID = T.ID;
