WITH A AS
    (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAXI
    FROM ECOLI_DATA 
    GROUP BY YEAR(DIFFERENTIATION_DATE))
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, A.MAXI-SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA E LEFT JOIN A ON YEAR(E.DIFFERENTIATION_DATE) = A.YEAR
ORDER BY A.YEAR, YEAR_DEV;
    
# WITH A AS (
#     SELECT 
#         YEAR(DIFFERENTIATION_DATE) AS YEAR,
#         MAX(SIZE_OF_COLONY) AS MAX_SIZE
#     FROM 
#         ECOLI_DATA 
#     GROUP BY 
#         YEAR(DIFFERENTIATION_DATE)
# )
# SELECT * FROM A;



# SELECT MAX(SIZE_OF_COLONY), YEAR(DIFFERENTIATION_DATE) AS YEAR, ID
#     # AS YEAR_DEV, ID
# FROM ECOLI_DATA
# GROUP BY YEAR;